# Generated by Django 4.2 on 2025-06-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
